config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'

  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  resources :courses do
    resources :events
  end
  resources :joins

end

app/models/join.rb
class Join < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
  before_action :set_join, only: [:show, :edit, :update, :destroy]

  # GET /joins
  # GET /joins.json
  def index
    @joins = Join.all
  end

  # GET /joins/1
  # GET /joins/1.json
  def show
  end

  # GET /joins/new
  def new
    @join = Join.new
  end

  # GET /joins/1/edit
  def edit
  end

  # POST /joins
  # POST /joins.json
  def create
    @join = Join.new(join_params)

    respond_to do |format|
      if @join.save
        format.html { redirect_to @join, notice: 'Join was successfully created.' }
        format.json { render :show, status: :created, location: @join }
      else
        format.html { render :new }
        format.json { render json: @join.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joins/1
  # PATCH/PUT /joins/1.json
  def update
    respond_to do |format|
      if @join.update(join_params)
        format.html { redirect_to @join, notice: 'Join was successfully updated.' }
        format.json { render :show, status: :ok, location: @join }
      else
        format.html { render :edit }
        format.json { render json: @join.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joins/1
  # DELETE /joins/1.json
  def destroy
    @join.destroy
    respond_to do |format|
      format.html { redirect_to joins_url, notice: 'Join was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_join
      @join = Join.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def join_params
      params.require(:join).permit(:user_id, :event_id)
    end
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/views/joins/_form.html.erb
<%= form_for(@join) do |f| %>
  <% if @join.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@join.errors.count, "error") %> prohibited this join from being saved:</h2>

      <ul>
      <% @join.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/joins/edit.html.erb
<h1>Editing Join</h1>

<%= render 'form' %>

<%= link_to 'Show', @join %> |
<%= link_to 'Back', joins_path %>

app/views/joins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Joins</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @joins.each do |join| %>
      <tr>
        <td><%= join.user %></td>
        <td><%= join.event %></td>
        <td><%= link_to 'Show', join %></td>
        <td><%= link_to 'Edit', edit_join_path(join) %></td>
        <td><%= link_to 'Destroy', join, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Join', new_join_path %>

app/views/joins/new.html.erb
<h1>New Join</h1>

<%= render 'form' %>

<%= link_to 'Back', joins_path %>

app/views/joins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @join.user %>
</p>

<p>
  <strong>Event:</strong>
  <%= @join.event %>
</p>

<%= link_to 'Edit', edit_join_path(@join) %> |
<%= link_to 'Back', joins_path %>